name: Testing
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install xlib
        pip install -Iv pyautogui==0.9.39
        pip install behave

    - name: Run unit tests for ahorcado logic
      run: |
        sudo apt-get install xvfb python3-tk python3-dev
        pip install pytest pytest-cov
        pytest --cov --cov-report=xml --ignore test_ahorcadoGUI.py
        xvfb-run -a -s "-screen 0 640x480x8" behave

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
