name: CI/CD Worflow deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    #needs: test
    steps:
    - name: Trigger render deploy hook
      run: |
        curl -X POST ${{ secrets.RENDER_HOOK }}
        echo The PR was merged