name: CI/CD Worflow
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
    types:
      - closed


jobs:
  deploy:
    #if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    #needs: test
    steps:
    - name: Trigger render deploy hook
      run: |
        curl -X POST ${{ secrets.RENDER_HOOK }}
        echo The PR was merged